services:
    InheritArticleBundle\EventListener\InheritArticleListener:
        arguments:
            - '@doctrine.dbal.default_connection'
            - '@contao.framework'
            - '@contao.image.picture_factory'
        public: true
