services:
    _instanceof:
        Contao\CoreBundle\Framework\FrameworkAwareInterface:
            calls:
                - ["setFramework", ["@contao.framework"]]

    contao_inherit_article.listener:
        class: InheritArticleBundle\EventListener\InheritArticleListener
        arguments: ['@doctrine.dbal.default_connection']
        public: true
